# Template for new migration files
 
"""initial schema

Revision ID: 859d69d120fc
Revises: None
Create Date: 2026-07-10 22:22:04.701513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '859d69d120fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('segment_type', sa.Enum('PHYSIO', 'URGENT_CARE', 'GP', name='segment_type_enum'), nullable=False),
    sa.Column('pms_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pms_integration_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_kind', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_kind', sa.String(), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('patients',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('name_prefix', sa.String(), nullable=True),
    sa.Column('nhi_number', sa.String(length=7), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('sex_at_birth', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('ethnicity', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('gms_status', sa.String(), nullable=True),
    sa.Column('registered_gp_name', sa.String(), nullable=True),
    sa.Column('registered_gp_practice', sa.String(), nullable=True),
    sa.Column('external_pms_patient_id', sa.String(), nullable=True),
    sa.Column('pms_vendor', sa.String(), nullable=True),
    sa.Column('pms_extension', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_organization_id'), 'patients', ['organization_id'], unique=False)
    op.create_table('practitioners',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('hpi_cpn', sa.String(length=6), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioners_organization_id'), 'practitioners', ['organization_id'], unique=False)
    op.create_table('surveys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', 'version')
    )
    op.create_index(op.f('ix_surveys_organization_id'), 'surveys', ['organization_id'], unique=False)
    op.create_table('consents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('accepted_text', sa.String(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'kind', 'version')
    )
    op.create_index(op.f('ix_consents_organization_id'), 'consents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_table('encounters',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('presentation_category', sa.String(), nullable=True),
    sa.Column('chief_complaint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('persistence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progression', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('onset_circumstance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('self_management', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('weight_change', sa.String(), nullable=True),
    sa.Column('functional_impact_score', sa.Integer(), nullable=True),
    sa.Column('character', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mitigating_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exacerbating_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comorbidities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ice_idea', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ice_concern', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ice_expectation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('encounter_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acc_claim_suspected', sa.Boolean(), nullable=False),
    sa.Column('acc_can_work', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_organization_id'), 'encounters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_table('body_structures',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('region_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sub_region_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('laterality', sa.String(), nullable=True),
    sa.Column('severity_score', sa.Integer(), nullable=True),
    sa.Column('character', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('radiation_status', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_structures_encounter_id'), 'body_structures', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_body_structures_organization_id'), 'body_structures', ['organization_id'], unique=False)
    op.create_table('flags',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fhir_system', sa.String(), nullable=True),
    sa.Column('fhir_code', sa.String(), nullable=True),
    sa.Column('fhir_display', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_encounter_id'), 'flags', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_flags_organization_id'), 'flags', ['organization_id'], unique=False)
    op.create_table('intake_fact_items',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fhir_system', sa.String(), nullable=True),
    sa.Column('fhir_code', sa.String(), nullable=True),
    sa.Column('fhir_display', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_fact_items_encounter_id'), 'intake_fact_items', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_intake_fact_items_organization_id'), 'intake_fact_items', ['organization_id'], unique=False)
    op.create_table('lilly_ai_interactions',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('prompt', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lilly_ai_interactions_encounter_id'), 'lilly_ai_interactions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_lilly_ai_interactions_organization_id'), 'lilly_ai_interactions', ['organization_id'], unique=False)
    op.create_table('practitioner_comments',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['practitioner_id'], ['practitioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_comments_encounter_id'), 'practitioner_comments', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_practitioner_comments_organization_id'), 'practitioner_comments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_practitioner_comments_practitioner_id'), 'practitioner_comments', ['practitioner_id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id', 'survey_id')
    )
    op.create_index(op.f('ix_survey_responses_encounter_id'), 'survey_responses', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_organization_id'), 'survey_responses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_survey_responses_survey_id'), 'survey_responses', ['survey_id'], unique=False)
    op.create_table('radiation_sites',
    sa.Column('body_structure_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('region_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['body_structure_id'], ['body_structures.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radiation_sites_body_structure_id'), 'radiation_sites', ['body_structure_id'], unique=False)
    op.create_index(op.f('ix_radiation_sites_organization_id'), 'radiation_sites', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_radiation_sites_organization_id'), table_name='radiation_sites')
    op.drop_index(op.f('ix_radiation_sites_body_structure_id'), table_name='radiation_sites')
    op.drop_table('radiation_sites')
    op.drop_index(op.f('ix_survey_responses_survey_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_organization_id'), table_name='survey_responses')
    op.drop_index(op.f('ix_survey_responses_encounter_id'), table_name='survey_responses')
    op.drop_table('survey_responses')
    op.drop_index(op.f('ix_practitioner_comments_practitioner_id'), table_name='practitioner_comments')
    op.drop_index(op.f('ix_practitioner_comments_organization_id'), table_name='practitioner_comments')
    op.drop_index(op.f('ix_practitioner_comments_encounter_id'), table_name='practitioner_comments')
    op.drop_table('practitioner_comments')
    op.drop_index(op.f('ix_lilly_ai_interactions_organization_id'), table_name='lilly_ai_interactions')
    op.drop_index(op.f('ix_lilly_ai_interactions_encounter_id'), table_name='lilly_ai_interactions')
    op.drop_table('lilly_ai_interactions')
    op.drop_index(op.f('ix_intake_fact_items_organization_id'), table_name='intake_fact_items')
    op.drop_index(op.f('ix_intake_fact_items_encounter_id'), table_name='intake_fact_items')
    op.drop_table('intake_fact_items')
    op.drop_index(op.f('ix_flags_organization_id'), table_name='flags')
    op.drop_index(op.f('ix_flags_encounter_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_body_structures_organization_id'), table_name='body_structures')
    op.drop_index(op.f('ix_body_structures_encounter_id'), table_name='body_structures')
    op.drop_table('body_structures')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_organization_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_organization_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_surveys_organization_id'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_practitioners_organization_id'), table_name='practitioners')
    op.drop_table('practitioners')
    op.drop_index(op.f('ix_patients_organization_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('organizations')
    # ### end Alembic commands ###
