"""RLS: roles, session functions, grants, and policies

Hand-written (not autogenerate) — implements docs/database/RLS.md in full.

MUST run after the first autogenerated migration (creates SQLAlchemy tables).

Checkpoint tables are owned by LangGraph. This migration applies
organization_id + RLS to them only if they already exist (after
`checkpointer.setup()`). If missing, app-table RLS still applies; add a
follow-up migration after setup to cover checkpoints.

Revision ID: rls_roles_policies_001
Revises: 859d69d120fc
Create Date: (fill in when you run this)
"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

revision: str = "rls_roles_policies_001"
down_revision: Union[str, None] = "859d69d120fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table: str) -> bool:
    return bool(
        op.get_bind()
        .execute(
            text(
                "SELECT EXISTS ("
                "  SELECT 1 FROM information_schema.tables"
                "  WHERE table_schema = 'public' AND table_name = :t"
                ")"
            ),
            {"t": table},
        )
        .scalar()
    )


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. Extension
    # ------------------------------------------------------------------
    op.execute('CREATE EXTENSION IF NOT EXISTS pgcrypto;')

    # ------------------------------------------------------------------
    # 2. Roles
    #    No passwords set here on purpose (CONTRIBUTING.md: nothing but
    #    .env.example goes in git). Set them separately, per environment,
    #    via `ALTER ROLE ... WITH PASSWORD '...'` from a secret you don't
    #    commit — locally that can just be a one-off psql command.
    # ------------------------------------------------------------------
    op.execute("""
        DO $$
        BEGIN
          IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'align_app') THEN
            CREATE ROLE align_app LOGIN;
          END IF;
          IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'align_engine') THEN
            CREATE ROLE align_engine LOGIN;
          END IF;
          IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'align_admin') THEN
            CREATE ROLE align_admin LOGIN;
          END IF;
        END $$;
    """)

    # ------------------------------------------------------------------
    # 3. Session-variable reader functions
    #    Set per-request via SET LOCAL from the FastAPI backend.
    #
    #    NOTE: current_practitioner_id() is a new addition, not in the
    #    original RLS.md — needed so practitioner_comments can enforce
    #    "only the comment's author may edit/delete it" (see §5's policy
    #    below), which needs to know *which* practitioner is calling, not
    #    just that the caller is a practitioner.
    # ------------------------------------------------------------------
    op.execute('CREATE SCHEMA IF NOT EXISTS app;')

    op.execute("""
        CREATE OR REPLACE FUNCTION app.current_organization_id() RETURNS uuid
        LANGUAGE sql STABLE AS $$
          SELECT NULLIF(current_setting('app.current_organization_id', true), '')::uuid;
        $$;
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION app.current_encounter_id() RETURNS uuid
        LANGUAGE sql STABLE AS $$
          SELECT NULLIF(current_setting('app.current_encounter_id', true), '')::uuid;
        $$;
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION app.current_practitioner_id() RETURNS uuid
        LANGUAGE sql STABLE AS $$
          SELECT NULLIF(current_setting('app.current_practitioner_id', true), '')::uuid;
        $$;
    """)
    op.execute("""
        CREATE OR REPLACE FUNCTION app.is_patient() RETURNS boolean
        LANGUAGE sql STABLE AS $$
          SELECT COALESCE(NULLIF(current_setting('app.is_patient', true), '')::boolean, false);
        $$;
    """)

    op.execute('GRANT USAGE ON SCHEMA app TO align_app, align_engine, align_admin;')
    op.execute('GRANT USAGE ON SCHEMA public TO align_app, align_engine, align_admin;')

    # ------------------------------------------------------------------
    # 4. Checkpoint tables: add organization_id + auto-populate trigger
    #
    #    LangGraph's own INSERTs never set organization_id (it doesn't
    #    know the column exists) — a BEFORE INSERT trigger derives it
    #    from `encounters.organization_id` via `thread_id` (== encounter
    #    id) so every checkpoint row is correctly scoped without touching
    #    LangGraph's code. Skipped until checkpointer.setup() creates them.
    # ------------------------------------------------------------------
    checkpoint_tables = [
        t
        for t in ("checkpoints", "checkpoint_writes", "checkpoint_blobs")
        if _table_exists(t)
    ]

    if checkpoint_tables:
        for table in checkpoint_tables:
            op.execute(
                f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS organization_id uuid;"
            )

        op.execute("""
            CREATE OR REPLACE FUNCTION app.set_checkpoint_organization_id() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
              IF NEW.organization_id IS NULL THEN
                SELECT organization_id INTO NEW.organization_id
                FROM encounters WHERE id = NEW.thread_id::uuid;
              END IF;
              RETURN NEW;
            END;
            $$;
        """)
        for table in checkpoint_tables:
            op.execute(f"""
                DROP TRIGGER IF EXISTS set_org_id ON {table};
                CREATE TRIGGER set_org_id BEFORE INSERT ON {table}
                FOR EACH ROW EXECUTE FUNCTION app.set_checkpoint_organization_id();
            """)

    # ------------------------------------------------------------------
    # 5. Grants, per role
    # ------------------------------------------------------------------
    align_app_rw = [
        "patients", "encounters", "body_structures", "radiation_sites",
        "flags", "intake_fact_items", "practitioners", "practitioner_comments",
        *checkpoint_tables,
    ]
    for table in align_app_rw:
        op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO align_app;')

    # consents / survey_responses: patient-writable, no DELETE needed
    for table in ("consents", "survey_responses"):
        op.execute(f'GRANT SELECT, INSERT ON {table} TO align_app;')

    # organizations: read-only for align_app — writes go through align_admin
    op.execute('GRANT SELECT ON organizations TO align_app;')

    # checkpoint_migrations: no tenant data, align_app just needs to read
    # LangGraph's own schema-version check
    if _table_exists("checkpoint_migrations"):
        op.execute('GRANT SELECT ON checkpoint_migrations TO align_app;')

    # align_engine: insert-only, audit_logs + lilly_ai_interactions only
    op.execute('GRANT INSERT ON audit_logs, lilly_ai_interactions TO align_engine;')

    # align_admin: read-only across everything, read/write on the admin tier
    admin_readonly = [
        "organizations", "patients", "consents", "encounters", "body_structures",
        "radiation_sites", "flags", "intake_fact_items", "practitioners",
        "practitioner_comments", "survey_responses",
    ]
    for table in admin_readonly:
        op.execute(f'GRANT SELECT ON {table} TO align_admin;')
    op.execute('GRANT SELECT, INSERT, UPDATE, DELETE ON audit_logs, lilly_ai_interactions, surveys TO align_admin;')

    # ------------------------------------------------------------------
    # 6. Enable + force RLS on every application table
    #    FORCE means even the table owner is subject to policy — no
    #    implicit bypass, matching the "no BYPASSRLS, ever" principle.
    # ------------------------------------------------------------------
    all_rls_tables = [
        "organizations", "patients", "consents", "encounters", "body_structures",
        "radiation_sites", "flags", "intake_fact_items", "practitioners",
        "practitioner_comments", "surveys", "survey_responses", "audit_logs",
        "lilly_ai_interactions",
        *checkpoint_tables,
    ]
    for table in all_rls_tables:
        op.execute(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;')
        op.execute(f'ALTER TABLE {table} FORCE ROW LEVEL SECURITY;')
    # checkpoint_migrations: deliberately no RLS — no tenant column, no per-session data

    # ------------------------------------------------------------------
    # 7. Policies
    # ------------------------------------------------------------------

    # --- organizations (RLS.md §1) ---
    op.execute("""
        CREATE POLICY tenant_read ON organizations FOR SELECT TO align_app
        USING (id = app.current_organization_id());
    """)
    op.execute("""
        CREATE POLICY admin_read ON organizations FOR SELECT TO align_admin
        USING (true);
    """)

    # --- patients (RLS.md §2) ---
    op.execute("""
        CREATE POLICY tenant_isolation_patient ON patients TO align_app
        USING (
          organization_id = app.current_organization_id()
          AND (NOT app.is_patient() OR id = (
            SELECT patient_id FROM encounters WHERE id = app.current_encounter_id()
          ))
        )
        WITH CHECK (
          organization_id = app.current_organization_id()
          AND (NOT app.is_patient() OR id = (
            SELECT patient_id FROM encounters WHERE id = app.current_encounter_id()
          ))
        );
    """)
    op.execute("""
        CREATE POLICY admin_read ON patients FOR SELECT TO align_admin USING (true);
    """)

    # --- consents (RLS.md §3) — patient-only, practitioners get nothing ---
    op.execute("""
        CREATE POLICY patient_own_consents ON consents TO align_app
        USING (
          organization_id = app.current_organization_id()
          AND app.is_patient()
          AND patient_id = (
            SELECT patient_id FROM encounters WHERE id = app.current_encounter_id()
          )
        )
        WITH CHECK (
          organization_id = app.current_organization_id()
          AND app.is_patient()
          AND patient_id = (
            SELECT patient_id FROM encounters WHERE id = app.current_encounter_id()
          )
        );
    """)
    op.execute("""
        CREATE POLICY admin_read ON consents FOR SELECT TO align_admin USING (true);
    """)

    # --- encounters (RLS.md §4) ---
    op.execute("""
        CREATE POLICY tenant_isolation_patient ON encounters TO align_app
        USING (
          organization_id = app.current_organization_id()
          AND (NOT app.is_patient() OR id = app.current_encounter_id())
        )
        WITH CHECK (
          organization_id = app.current_organization_id()
          AND (NOT app.is_patient() OR id = app.current_encounter_id())
        );
    """)
    op.execute("""
        CREATE POLICY admin_read ON encounters FOR SELECT TO align_admin USING (true);
    """)

    # --- body_structures, flags, intake_fact_items (RLS.md §4, encounter_id-scoped) ---
    for table in ("body_structures", "flags", "intake_fact_items"):
        op.execute(f"""
            CREATE POLICY tenant_isolation_patient ON {table} TO align_app
            USING (
              organization_id = app.current_organization_id()
              AND (NOT app.is_patient() OR encounter_id = app.current_encounter_id())
            )
            WITH CHECK (
              organization_id = app.current_organization_id()
              AND (NOT app.is_patient() OR encounter_id = app.current_encounter_id())
            );
        """)
        op.execute(f"""
            CREATE POLICY admin_read ON {table} FOR SELECT TO align_admin USING (true);
        """)

    # --- radiation_sites (RLS.md §4, one join further via body_structures) ---
    op.execute("""
        CREATE POLICY tenant_isolation_patient ON radiation_sites TO align_app
        USING (
          organization_id = app.current_organization_id()
          AND (NOT app.is_patient() OR body_structure_id IN (
            SELECT id FROM body_structures WHERE encounter_id = app.current_encounter_id()
          ))
        )
        WITH CHECK (
          organization_id = app.current_organization_id()
          AND (NOT app.is_patient() OR body_structure_id IN (
            SELECT id FROM body_structures WHERE encounter_id = app.current_encounter_id()
          ))
        );
    """)
    op.execute("""
        CREATE POLICY admin_read ON radiation_sites FOR SELECT TO align_admin USING (true);
    """)

    # --- practitioners (RLS.md §5) ---
    op.execute("""
        CREATE POLICY practitioner_only ON practitioners TO align_app
        USING (organization_id = app.current_organization_id() AND NOT app.is_patient())
        WITH CHECK (organization_id = app.current_organization_id() AND NOT app.is_patient());
    """)
    op.execute("""
        CREATE POLICY admin_read ON practitioners FOR SELECT TO align_admin USING (true);
    """)

    # --- practitioner_comments (RLS.md §5 + author-only edit/delete from README) ---
    op.execute("""
        CREATE POLICY read_within_org ON practitioner_comments FOR SELECT TO align_app
        USING (organization_id = app.current_organization_id() AND NOT app.is_patient());
    """)
    op.execute("""
        CREATE POLICY insert_within_org ON practitioner_comments FOR INSERT TO align_app
        WITH CHECK (
          organization_id = app.current_organization_id()
          AND NOT app.is_patient()
          AND practitioner_id = app.current_practitioner_id()
        );
    """)
    op.execute("""
        CREATE POLICY author_only_update ON practitioner_comments FOR UPDATE TO align_app
        USING (
          organization_id = app.current_organization_id()
          AND practitioner_id = app.current_practitioner_id()
        )
        WITH CHECK (
          organization_id = app.current_organization_id()
          AND practitioner_id = app.current_practitioner_id()
        );
    """)
    op.execute("""
        CREATE POLICY author_only_delete ON practitioner_comments FOR DELETE TO align_app
        USING (
          organization_id = app.current_organization_id()
          AND practitioner_id = app.current_practitioner_id()
        );
    """)
    op.execute("""
        CREATE POLICY admin_read ON practitioner_comments FOR SELECT TO align_admin USING (true);
    """)

    # --- admin-only tier: audit_logs, lilly_ai_interactions, surveys (RLS.md §6) ---
    op.execute("""
        CREATE POLICY engine_insert_only ON audit_logs FOR INSERT TO align_engine
        WITH CHECK (true);
    """)
    op.execute("""
        CREATE POLICY engine_insert_only ON lilly_ai_interactions FOR INSERT TO align_engine
        WITH CHECK (true);
    """)
    for table in ("audit_logs", "lilly_ai_interactions", "surveys"):
        op.execute(f"""
            CREATE POLICY admin_full_access ON {table} TO align_admin
            USING (true) WITH CHECK (true);
        """)

    # --- survey_responses (RLS.md §6 correction — patient-writable, practitioners blocked) ---
    op.execute("""
        CREATE POLICY patient_own_response ON survey_responses TO align_app
        USING (
          organization_id = app.current_organization_id()
          AND app.is_patient()
          AND encounter_id = app.current_encounter_id()
        )
        WITH CHECK (
          organization_id = app.current_organization_id()
          AND app.is_patient()
          AND encounter_id = app.current_encounter_id()
        );
    """)
    op.execute("""
        CREATE POLICY admin_read ON survey_responses FOR SELECT TO align_admin USING (true);
    """)

    # --- checkpoints, checkpoint_writes, checkpoint_blobs (RLS.md §7) ---
    for table in checkpoint_tables:
        op.execute(f"""
            CREATE POLICY tenant_isolation_patient ON {table} TO align_app
            USING (
              organization_id = app.current_organization_id()
              AND (NOT app.is_patient() OR thread_id = app.current_encounter_id()::text)
            )
            WITH CHECK (
              organization_id = app.current_organization_id()
              AND (NOT app.is_patient() OR thread_id = app.current_encounter_id()::text)
            );
        """)
    # No organization_id IS NULL exception anywhere — see RLS.md §8.


def downgrade() -> None:
    # Policies and grants are dropped implicitly with the tables in the
    # model migration's downgrade; this only needs to reverse what it
    # added independently of table existence.
    op.execute('DROP FUNCTION IF EXISTS app.set_checkpoint_organization_id() CASCADE;')
    op.execute('DROP FUNCTION IF EXISTS app.is_patient();')
    op.execute('DROP FUNCTION IF EXISTS app.current_practitioner_id();')
    op.execute('DROP FUNCTION IF EXISTS app.current_encounter_id();')
    op.execute('DROP FUNCTION IF EXISTS app.current_organization_id();')
    op.execute('DROP SCHEMA IF EXISTS app;')
    op.execute('DROP ROLE IF EXISTS align_admin;')
    op.execute('DROP ROLE IF EXISTS align_engine;')
    op.execute('DROP ROLE IF EXISTS align_app;')