/**
 * Mandarin (简体中文) labels for body-diagram path IDs.
 * Keyed by the canonical SVG path id from bodydiagram_list.json.
 * Unlisted path IDs fall back to the procedural English label.
 */
export const BODY_REGION_LABELS_ZH: Readonly<Record<string, string>> = {
  // Arm — left
  Select_LeftHand: "左手",
  Select_LeftWrist: "左手腕",
  Select_LeftForearm: "左前臂",
  Select_LeftTricep: "左肱三头肌",
  Select_LeftShoulder: "左肩",
  Select_LeftBicep: "左肱二头肌",
  // Arm — right
  Select_RightHand: "右手",
  Select_RightWrist: "右手腕",
  Select_RightForearm: "右前臂",
  Select_RightTricep: "右肱三头肌",
  Select_RightShoulder: "右肩",
  Select_RightBicep: "右肱二头肌",

  // Face
  Select_Neck: "颈部",
  Select_LeftEar: "左耳",
  Select_RightEar: "右耳",
  Select_Chin: "下巴",
  Select_Mouth: "嘴",
  Select_Nose: "鼻子",
  Select_LeftEye: "左眼",
  Select_RightEye: "右眼",
  Select_LeftSide: "左脸",
  Select_RightSide: "右脸",
  Select_Forehead: "前额",

  // Female legs — back
  Select_FemaleLegs_Back_Right_LowerCalf: "右小腿下部",
  Select_FemaleLegs_Back_Left_LowerCalf: "左小腿下部",
  Select_FemaleLegs_Back_Right_Calf: "右小腿",
  Select_FemaleLegs_Back_Left_Calf: "左小腿",
  Select_FemaleLegs_Back_Right_BackofKnee: "右腘窝（膝后）",
  Select_FemaleLegs_Back_Left_BackofKnee: "左腘窝（膝后）",
  Select_FemaleLegs_Back_Right_Hamstring: "右腘绳肌",
  Select_FemaleLegs_Back_Left_Hamstring: "左腘绳肌",
  // Female legs — front
  Select_FemaleLegs_Front_LeftAnkle: "左踝",
  Select_FemaleLegs_Front_RightAnkle: "右踝",
  Select_FemaleLegs_Front_LeftFoot: "左脚",
  Select_FemaleLegs_Front_RightFoot: "右脚",
  Select_FemaleLegs_Front_LeftShin: "左胫骨",
  Select_FemaleLegs_Front_RightShin: "右胫骨",
  Select_FemaleLegs_Front_LeftKnee: "左膝",
  Select_FemaleLegs_Front_RightKnee: "右膝",
  Select_FemaleLegs_Front_Left_InnerThigh: "左大腿内侧",
  Select_FemaleLegs_Front_Right_InnerThigh: "右大腿内侧",
  Select_FemaleLegs_Front_Left_OuterThigh: "左大腿外侧",
  Select_FemaleLegs_Front_Right_OuterThigh: "右大腿外侧",

  // Female torso — back
  Select_Female_TorsoBack_Right_Lateral_LowerBack: "右下背外侧",
  Select_Female_TorsoBack_Left_Lateral_LowerBack: "左下背外侧",
  Select_Female_TorsoBack_Right_Lats: "右背阔肌",
  Select_Female_TorsoBack_Left_Lats: "左背阔肌",
  Select_Female_TorsoBack_Right_Medial_LowerBack: "右下背内侧",
  Select_Female_TorsoBack_Left_Medial_LowerBack: "左下背内侧",
  Select_Female_TorsoBack_Right_ShoulderBlade: "右肩胛骨",
  Select_Female_TorsoBack_Left_ShoulderBlade: "左肩胛骨",
  Select_Female_TorsoBack_Right_Medial_MidBack: "右中背内侧",
  Select_Female_TorsoBack_Left_Medial_MidBack: "左中背内侧",
  Select_Female_TorsoBack_Right_Trapezeum: "右斜方肌",
  Select_Female_TorsoBack_Left_Trapezeum: "左斜方肌",
  // Female torso — front
  Select_Female_TorsoFront_Left_LowerChest: "左下胸",
  Select_Female_TorsoFront_Right_LowerChest: "右下胸",
  Select_Female_TorsoFront_Left_UpperChest: "左上胸",
  Select_Female_TorsoFront_Right_UpperChest: "右上胸",
  Select_Female_TorsoFront_Right_RibCage: "右肋骨",
  Select_Female_TorsoFront_Left_RibCage: "左肋骨",
  Select_Female_TorsoFront_Epigastrium: "上腹部（心窝）",
  Select_Female_TorsoFront_Umbellical: "脐周",
  Select_Female_TorsoFront_Lower_MiddleQuadrant: "下腹中部",
  Select_Female_TorsoFront_Left_UpperQuadrant: "左上腹",
  Select_Female_TorsoFront_Left_UpperQuadrant_2: "左上腹（2）",
  Select_Female_TorsoFront_Left_Flank: "左侧腹",
  Select_Female_TorsoFront_Left_Flank_2: "左侧腹（2）",
  Select_Female_TorsoFront_Left_LowerQuadrant: "左下腹",
  Select_Female_TorsoFront_Right_LowerQuadrant: "右下腹",
  Select_Female_TorsoFront_Middle_Chest: "胸部中央",

  // Male legs — back
  Select_MaleLegs_Back_Right_LowerCalf: "右小腿下部",
  Select_MaleLegs_Back_Left_LowerCalf: "左小腿下部",
  Select_MaleLegs_Back_Right_Calf: "右小腿",
  Select_MaleLegs_Back_Left_Calf: "左小腿",
  Select_MaleLegs_Back_Right_BackofKnee: "右腘窝（膝后）",
  Select_MaleLegs_Back_Left_BackofKnee: "左腘窝（膝后）",
  Select_MaleLegs_Back_Right_HamString: "右腘绳肌",
  Select_MaleLegs_Back_Left_HamString: "左腘绳肌",
  // Male legs — front
  Select_MaleLegs_Front_LeftFoot: "左脚",
  Select_MaleLegs_Front_RightFoot: "右脚",
  Select_MaleLegs_Front_LeftAnkle: "左踝",
  Select_MaleLegs_Front_RightAnkle: "右踝",
  Select_MaleLegs_Front_LeftShin: "左胫骨",
  Select_MaleLegs_Front_RightShin: "右胫骨",
  Select_MaleLegs_Front_LeftKnee: "左膝",
  Select_MaleLegs_Front_RightKnee: "右膝",
  Select_MaleLegs_Front_Left_InnerThigh: "左大腿内侧",
  Select_MaleLegs_Front_Right_InnerThigh: "右大腿内侧",
  Select_MaleLegs_Front_Left_OuterThigh: "左大腿外侧",
  Select_MaleLegs_Front_Right_OuterThigh: "右大腿外侧",

  // Male torso — back
  Select_Right_Lateral_LowerBack: "右下背外侧",
  Select_Left_Lateral_LowerBack: "左下背外侧",
  Select_Right_Lats: "右背阔肌",
  Select_Left_Lats: "左背阔肌",
  Select_Right_Medial_LowerBack: "右下背内侧",
  Select_Left_Medial_LowerBack: "左下背内侧",
  Select_Right_ShoulderBlade: "右肩胛骨",
  Select_Left_ShoulderBlade: "左肩胛骨",
  Select_Right_Medial_MidBack: "右中背内侧",
  Select_Left_Medial_MidBack: "左中背内侧",
  Select_Right_Trapezeum: "右斜方肌",
  Select_Left_Trapezeum: "左斜方肌",
  // Male torso — front
  Select_Lower_MiddleQuadrant: "下腹中部",
  Select_Left_LowerQuadrant: "左下腹",
  Select_Right_LowerQuadrant: "右下腹",
  Select_Left_Chest: "左胸",
  Select_Right_Chest: "右胸",
  Select_Left_RibCage: "左肋骨",
  Select_Right_RibCage: "右肋骨",
  Select_Epigastrium: "上腹部（心窝）",
  Select_Umbellical: "脐周",
  Select_Left_UpperQuadrant: "左上腹",
  Select_Right_UpperQuadrant: "右上腹",
  Select_Left_Flank: "左侧腹",
  Select_Right_Flank: "右侧腹",
  Select_MiddleChest: "胸部中央",
};
